sudo: required
dist: trusty
language: php
env:
    #global environmental variables control magento install parameters
    #see also hosts in addons.
    global:
        - PULSESTORM_MAGE2_FAKE_URL=http://magento-2-travis.dev
        - PULSESTORM_MAGE2_ADMIN_EMAIL=roman.hutterer@copex.io
        - PULSESTORM_MAGE2_ADMIN_FIRST_NAME=Roman
        - PULSESTORM_MAGE2_ADMIN_LAST_NAME=Hutterer
        - PULSESTORM_MAGE2_ADMIN_USERNAME=admin
        - PULSESTORM_MAGE2_ADMIN_PASSWORD=ih3artmagento
        - PULSESTORM_MAGE2_ADMIN_DBNAME=magento_2_travis
        - PULSESTORM_PESTLE_URL=http://pestle.pulsestorm.net
        - PULSESTORM_COMPOSER_REPOSITORY_TO_TEST=https://github.com/CopeX/CopeX_VatFix.git
        - PULSESTORM_COMPOSER_PACKAGE_TO_TEST=copex/vatfix
addons:
    hosts:
        # should match PULSESTORM_MAGE2_FAKE_URL above
        - magento-2-travis.dev
    apt:
        packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6

jobs:
    include:
        -   php: 7.0
            env:
                - MAGENTO_VERSION=2.2.0
        -   php: 7.1
            env:
                - MAGENTO_VERSION=2.2.0
        -   php: 7.1
            env:
                - MAGENTO_VERSION=2.3.0
        -   php: 7.2
            env:
                - MAGENTO_VERSION=2.3.0
before_script:
    # some useful debugging stuff for travis
    #- curl http://magento-2-travis.dev/index.php
    #- curl http://magento-2-travis.dev/  
    #- sudo find /var/log/apache2 -exec cat '{}' \;      
    #- sudo cat /etc/apache2/sites-available/000-default.conf
    #- sudo cat /etc/apache2/sites-enabled/000-default.conf    
    #- sudo apachectl -V
    #- sudo apache2ctl -V
    #- ls -lh $TRAVIS_BUILD_DIR
    #- sudo ls /etc/apache2/sites-available
    #- sudo ls /etc/apache2/sites-enabled
    #- pwd    
    #    
    # get latest composer 
    - composer selfupdate
    # disable xdebug for perf    
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    # add mysql 5.6 database
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    # add apache
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    #   enable php-fpm -- www.conf.default is PHP 7 only, so we dev/null any copy problems    
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #   awful hack used during travis debugging that I swear I'm going to remove
    #   but then again you're reading this so I didn't remove it and **sigh**    
    - sudo chmod 777 /home /home/travis /home/travis/build

    #   configure apache virtual hosts, assumes 000-default.conf is there
    - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    # restart apache
    - sudo service apache2 restart

    # clone main magento github repository
    - git clone https://github.com/magento/magento2

    # install Magento
    - cd magento2
    - git checkout tags/$MAGENTO_VERSION
    # add composer package under test, composer require will trigger update/install
    - composer config repositories.travis_to_test git https://github.com/CopeX/CopeX_VatFix.git
    - composer require copex/vatfix dev-master
    # run installation command using evn variables set above
    - php bin/magento setup:install --admin-email "$PULSESTORM_MAGE2_ADMIN_EMAIL" --admin-firstname "$PULSESTORM_MAGE2_ADMIN_FIRST_NAME" --admin-lastname "$PULSESTORM_MAGE2_ADMIN_LAST_NAME" --admin-password "$PULSESTORM_MAGE2_ADMIN_PASSWORD" --admin-user "$PULSESTORM_MAGE2_ADMIN_USERNAME" --backend-frontname admin --base-url "$PULSESTORM_MAGE2_FAKE_URL" --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
    # test that magento is installed
    - curl "$PULSESTORM_MAGE2_FAKE_URL/index.php" > /tmp/output.txt

script:
    - ./vendor/bin/phpunit -c ./dev/tests/unit/phpunit.xml.dist ./vendor/copex/vatfix/Test/Unit/Plugin/UidTest.php
